# Generated by Django 5.1.1 on 2024-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teacher_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
